version: "1.0"
stages:
  - "clone"
  - "validate"
  - "build"
  - "deployment"

steps:
  clone:
    stage: "clone"
    title: "Cloning repository"
    type: "git-clone"
    repo: "thinkbiggerltd/helm-promotion-sample-app"
    revision: '${{CF_REVISION}}'
  # prechecks:
  #   type: parallel
  #   stage: 'validate'
  #   steps:
  #     lint:
  #       title: Lint
  #       working_directory: "${{clone}}"
  #       image: golangci/golangci-lint:v1.33.0
  #       commands:
  #         - golangci-lint run -v .
  #     securityAnalysis:
  #       title: Security Scan
  #       working_directory: "${{clone}}"
  #       image: 'securego/gosec:v2.5.0'
  #       commands:
  #         - gosec ./...


  build:
    stage: "build"
    title: "Building Docker image"
    type: "build"
    image_name: thinkbiggerltd/helm-promotion
    working_directory: "${{clone}}"
    tags:
    - "latest"
    - '${{CF_SHORT_REVISION}}'
    dockerfile: "Dockerfile"
    # disable_push: true
    # registry: github

  PushToDockerRegistry:
    type: push
    candidate: '${{build}}'
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    # registry: 'github'

  deployStaging:
      title: Deploying to Staging
      type: deploy
      kind: kubernetes
      cluster: 'codefresh-sandbox' #the name specified when you added the cluster
      namespace: staging #the namespace you wish to deploy into
      service: helm-promotion #the service you would like to update the deployment in
      candidate:
        image: '${{build}}'
        registry: github


  # deployStaging:
  #   stage: deployment
  #   title: Deploying to Staging
  #   type: helm
  #   working_directory: ./helm-promotion-sample-app
  #   arguments:
  #     action: install
  #     chart_name: ./chart/sample-app
  #     release_name: example-staging
  #     helm_version: 3.0.2
  #     kube_context: 'garrett@thinkbigger.ie'
  #     namespace: staging
  #     custom_value_files:
  #     - ./chart/values-staging.yaml
  #   when:
  #     branch:
  #       ignore:
  #         - master      

  # askForPermission:
  #   stage: prod
  #   type: pending-approval
  #   title: Deploy to production?

  # deployProd:
  #   stage: deployment
  #   title: Deploying to Production
  #   type: helm
  #   working_directory: ./helm-promotion-sample-app
  #   arguments:
  #     action: install
  #     chart_name: ./chart/sample-app
  #     release_name: example-prod
  #     helm_version: 3.0.2
  #     kube_context: 'garrett@thinkbigger.ie'
  #     namespace: production
  #     custom_value_files:
  #     - ./chart/values-prod.yaml
  #   when:
  #     branch:
  #       only:
  #         - master