version: "1.0"
stages:
  - "clone"
  - "build"
  - "testing"
  - "prod"

steps:
  clone:
    stage: "clone"
    title: "Cloning repository"
    type: "git-clone"
    repo: "thinkbiggerltd/helm-promotion-sample-app"
    revision: '${{CF_REVISION}}'

  build:
    stage: "build"
    title: "Building Docker image"
    type: "build"
    image_name: helm-promotion
    working_directory: "${{clone}}"
    tags:
    - "latest"
    - '${{CF_SHORT_REVISION}}'
    dockerfile: "Dockerfile"
    disable_push: true
    # registry: dockerhub

  myTests:
    stage: "testing"
    title: Integration Tests
    type: freestyle
    working_directory: "${{clone}}"
    arguments:
      image: 'byrnedo/alpine-curl'
      commands:
        - "curl http://app:8080/health"
    services:
      composition:
        app:
          image: '${{build_app_image}}'
          ports:
            - 8080

  deployProd:
    title: Deploying to Production
    type: helm
    stage: prod
    working_directory: ./helm-promotion-sample-app
    arguments:
      action: install
      chart_name: ./chart/sample-app
      release_name: example-prod
      helm_version: 3.0.2
      kube_context: 'garrett@thinkbigger.ie'
      namespace: production
      custom_value_files:
      - ./chart/values-prod.yaml

  # askForPermission:
  #   stage: prod
  #   type: pending-approval
  #   title: Deploy to production?

  # deployProd:
  #   stage: deployment
  #   title: Deploying to Production
  #   type: helm
  #   working_directory: ./helm-promotion-sample-app
  #   arguments:
  #     action: install
  #     chart_name: ./chart/sample-app
  #     release_name: example-prod
  #     helm_version: 3.0.2
  #     kube_context: 'garrett@thinkbigger.ie'
  #     namespace: production
  #     custom_value_files:
  #     - ./chart/values-prod.yaml
  #   when:
  #     branch:
  #       only:
  #         - master